name = "sakura-share-test"
main = "worker.js"
compatibility_date = "2023-01-01"
workers_dev = false

[[d1_databases]]
binding = "DB"
database_name = "sakura-share-test"
database_id = "f802fabd-618e-4e5e-b192-8c88d9f44117"

[placement]
mode = "smart"

routes = [
    { pattern = "sakura-share.1percentsync.games", custom_domain = true }
]