name = "sakura-share"
main = "worker.js"
compatibility_date = "2023-01-01"

[[d1_databases]]
binding = "DB"
database_name = "sakura-share"
database_id = "9fb790c8-d305-4739-b920-5693cb223bc4"

[placement]
mode = "smart"

routes = [
  "sakura-share.one/register-node",
  "sakura-share.one/verify-node",
  "sakura-share.one/delete-node",
  "sakura-share.one/completion",
  "sakura-share.one/completions",
  "sakura-share.one/v1/chat/completions",
  "sakura-share.one/health",
  "sakura-share.1percentsync.games/*"
]