name = "sakura-share-7b"
main = "worker.js"
compatibility_date = "2023-01-01"
workers_dev = false

[[d1_databases]]
binding = "DB"
database_name = "7b"
database_id = "6b702303-64a6-4eff-ba0b-617e47aa2046"

[placement]
mode = "smart"

routes = [
    { pattern = "7b.sakura-share.one", custom_domain = true }
]